[package]
name = "xsec-cli"
version = "0.0.1"
edition = "2024"
description = "Command-line environment encryption powered by XSec."
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/nashaofu/xsec.git"

[[bin]]
name = "xsec"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
dotenvy = "0.15.7"
rpassword = "7.5.4"
secrecy = "0.10.3"
tempfile = "3.27.0"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["fs", "io-std", "io-util", "macros", "process", "rt-multi-thread"] }
xsec = { version = "0.0.1", path = "../xsec", default-features = false, features = ["file-storage", "password-protector", "system-protector"] }
zeroize = "1.9.0"
