[package]
name = "xsec"
version = "0.0.1"
edition = "2024"
description = "Cross-platform data encryption and key protection library."
license = "Apache-2.0"
repository = "https://github.com/nashaofu/xsec.git"

[features]
default = ["file-storage", "password-protector", "system-protector"]
file-storage = ["dep:tempfile", "tokio/fs"]
password-protector = ["dep:argon2"]
system-protector = ["dep:windows", "dep:windows-future"]

[dependencies]
aes-gcm = { version = "0.11.1", features = ["zeroize"] }
argon2 = { version = "0.6.0", features = ["zeroize"], optional = true }
getrandom = { version = "0.4.3", features = ["std"] }
hkdf = "0.13.0"
hmac = "0.13.0"
secrecy = "0.10.3"
sha2 = "0.11.0"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt"] }
tempfile = { version = "3.27.0", optional = true }
zeroize = "1.9.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61.3", optional = true, features = ["Security_Credentials", "Security_Cryptography", "Foundation", "Storage_Streams", "Win32", "Win32_Security", "Win32_Security_Cryptography"] }
windows-future = { version = "0.2.1", optional = true, features = ["std"] }

[dev-dependencies]
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["full"] }

[[example]]
name = "password"
required-features = ["file-storage", "password-protector"]

[[example]]
name = "system"
required-features = ["file-storage", "system-protector"]

[[example]]
name = "system_bypass"
required-features = ["system-protector"]
